First homework (task_1) by Krivoruchko Dmitry
AlgorithmsDafeMipt2024/spring_homework pull request #10
Opened 2024-02-19 23:19 UTC by UmbrellaLeaf5

2024-02-24 12:05 UTC, LostPointer requested changes

2024-02-24 12:05 UTC, LostPointer commented on task_01/src/test.cpp
>  }
можно ещё проверить пустой вектор, и например если 1 элемент в векторе

2024-02-24 12:05 UTC, LostPointer commented on task_01/src/two_sum.hpp
> +  size_t fir = 0;
символы экономим? first

2024-02-24 12:05 UTC, LostPointer commented on task_01/src/utilities.hpp
> +inline void PrintToConsole(const std::vector<Type>& vec) {
а можно перегрузить operator<<, так даже лучше выглядит)

2024-03-02 10:42 UTC, LostPointer requested changes

2024-03-02 10:42 UTC, LostPointer commented on task_01/src/main.cpp
> +  // cout << vec << std::endl;
давай уберем закомментированный код

2024-03-02 10:42 UTC, LostPointer commented on task_01/src/two_sum.hpp
> +// (и да, я не хочу париться с проверкой на то,)
про концепты знаешь?
https://habr.com/ru/companies/yandex_praktikum/articles/556816/
https://en.cppreference.com/w/cpp/language/constraints

это можно не делать, скорее для информации, будет только плюсом если сделаешь) нет так все равно все хорошо выглядит

2024-03-30 17:37 UTC, UmbrellaLeaf5 commented
сюда Stack случайно попал, когда я решил замерджиться с main, больше постараюсь так не делать :')

2024-04-01 19:59 UTC, closed without merging

2024-04-01 19:59 UTC, UmbrellaLeaf5 commented
закрываю, чтобы изменения в main не продолжали сюда добавляться