Homework 2
AlgorithmsDafeMipt2024/spring_homework pull request #40
Opened 2024-05-04 13:28 UTC by gulyonatyoma

Task_02 to Task_06

2024-05-11 09:35 UTC, LostPointer requested changes

2024-05-11 09:35 UTC, LostPointer commented on task_02/src/stack.hpp
> +  CustomClass& val = top_->data;
undefined behavior тут, сохраняешь ссылку на поле элемента который потом удаляешь

2024-05-11 09:35 UTC, LostPointer commented on task_03/src/temperature.cpp
> +  for (int i = temperature.size() - 1; i >= 0; i--) {
тут сложность О(n**2), можно за линейную

2024-05-11 09:35 UTC, LostPointer commented on task_04/src/heap.cpp
> +int Heap::DelMin() {
давай не экономить символы: DelMinimum

2024-05-11 09:35 UTC, LostPointer commented on task_04/src/test.cpp
> +TEST(heap, Test1) {
насыпь по больше тестов

2024-05-11 09:35 UTC, LostPointer commented on task_05/src/sort.hpp
> +  merge_two_sorted_arrays(
по кодстайлу нужно называть функции MergeTwoSortedArrays

2024-06-16 20:19 UTC, LostPointer requested changes

2024-06-16 20:19 UTC, LostPointer commented on task_02/src/stack.hpp
> +#include <concepts/comparable.hpp>
давай в таком порядке и пустой строкой:
```
#include <stack>
#include <stdexcept>

#include <concepts/comparable.hpp>
#include <concepts/constructable.hpp>
#include <listnode.hpp>
```

2024-06-16 20:19 UTC, LostPointer commented on task_02/src/test.cpp
> +TEST(EmptyStack, Simple) {
для стека с минимумом тоже хорошо бы тест на пустой стек сделать тест

2024-06-16 20:19 UTC, LostPointer commented on task_03/src/temperature.cpp
> +std::vector<unsigned int> Solve(std::vector<int> temperature) {
давай по лучше придумаем название для функции

2024-06-16 20:19 UTC, LostPointer commented on task_05/src/sort.hpp
> +template <constructable CustomClass>
тут лучше бы подошло constructable_and_comparable

2024-06-16 20:19 UTC, LostPointer commented on task_06/src/n_order_statistics.hpp
> +size_t partition(std::vector<CustomClass>& data_array, size_t left_index,
Partition

2024-06-16 20:19 UTC, LostPointer commented on task_06/src/n_order_statistics.hpp
> +CustomClass n_order_statistics(std::vector<CustomClass> data_array,
NthOrderStatistics

2024-06-16 22:57 UTC, gulyonatyoma commented on task_02/src/stack.hpp
> +#include <concepts/comparable.hpp>
clang format сам поправляет эти строчки инклюдов

2024-12-17 06:34 UTC, closed without merging